version: "3.9"

networks:
  app-net:
    name: termnet
    driver: bridge

volumes:
  minio-data:
  mongo-data:
  redis-data:

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    volumes:
      - minio-data:/data
    networks:
      - app-net
    restart: unless-stopped

  redis:
    image: redis:8.0-rc1
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-net
    restart: unless-stopped

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: my-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    restart: unless-stopped

  term-backend:
    image: term-backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo
      - redis
      - minio
    networks:
      - app-net
    restart: unless-stopped

  term-frontend:
    image: term-frontend
    ports:
      - "3000:3000"
    depends_on:
      - term-backend
    networks:
      - app-net
    restart: unless-stopped
